REWRITE_PROMPT_TEMPLATES = {
    "gate_rewrite_v1": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Key idea:\n"
        "- Assume you already have the correct answer to the user query.\n"
        "- The documents we want are the ones that would be used as core evidence or justification for that answer.\n"
        "- These evidence documents are often more abstract than the surface query.\n\n"
        "Task:\n"
        "- First, write a 1-2 sentence Plan that states the user's core intent and what kind of evidence would justify the answer.\n"
        "- Use the context summaries only as hints (not ground truth).\n"
        "- Produce 2-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
        "- Avoid near-duplicates; keep each item short and retrieval-friendly.\n"
        "- Evidence forms may include (not exhaustive): theory/mechanism, entity/fact, analogy/example, method/metric, canonical reference.\n\n"
        "Output JSON only:\n"
        "{\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Possible_Answer_Docs\": [\n"
        "    \"...\",\n"
        "    \"...\",\n"
        "    \"...\"\n"
        "  ]\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Context Summaries:\n{gate_descs}\n"
    ),
    "stepback_json": (
        "Given a query, the provided passages (most of which may be incorrect or irrelevant), and the previous round's answer (if any), "
        "your goal is to analyze the candidate passages retrieved for the query, "
        "identify which of them are strictly relevant to the user's true intent, "
        "and then refine the set of answer documents accordingly. "
        "Each refined document must be strictly relevant: it should either contain the "
        "exact answer or provide abstractive-level theory, evidence, or background that is "
        "necessary for that answer.\n\n"
        "Output Format:\n"
        "You must output a single JSON object with the following keys:\n"
        "- \"Plan\": A detailed string where you analyze availability of information and plan your selection. Follow the planning steps below.\n"
        "- \"Possible_Answer_Docs\": A JSON object with keys as document types (\"Theory\", \"Entity\", \"Example\", \"Other\") and values as strings representing distinct answer documents.\n\n"
        "Planning Steps (for the \"Plan\" field):\n"
        "1. Precisely identify what information the user is seeking "
        "(e.g., why / how / what / what is this called / which part) and what type of "
        "answer would satisfy them (e.g., concept name, theory, explanation, concrete "
        "entity, worked example).\n"
        "2. If the query is explicitly or implicitly asking 'what is this called?', "
        "generate diverse hypotheses for the name of the phenomenon, object, or concept.\n"
        "3. Abstraction: infer which academic terms, scientific theories, mathematical "
        "models, canonical methods, or standard resources lie behind this question and "
        "would be cited in a strictly correct answer.\n"
        "4. Consider alternative ways the answer might be supported: a direct definition, "
        "background theory, canonical examples, or reference websites.\n"
        "5. For causal or explanatory questions (why/how), identify multiple theoretical "
        "frameworks that offer different explanations, including mainstream, alternative, "
        "and controversial perspectives if mentioned in the query.\n"
        "6. For each Candidate Passage, judge which part of the user's query does the passage address. Then, "
        "identify the common wrong direction (topic, answer type, or framing) suggested by "
        "the Candidate Passages, and treat this as a negative constraint. Plan how to "
        "refine the answer documents to avoid that direction and instead explore a different, more "
        "plausible interpretation aligned with the user's wording.\n"
        "Ensure that every generated document contributes directly and strictly to such an "
        "answer (no loosely related or merely interesting content).\n\n"
        "Final Answer Requirements (for the \"Answer documents\" field):\n"
        "Include 3-5 distinct answer-document entries:\n"
        "- 1: Concept/Theory-focused (academic terms, principles, models).\n"
        "- 2: Entity/Fact-focused (specific names, objects, or concrete facts).\n"
        "- 3: Broad Context/Evidence-focused (surveys, experiments, or background "
        "that support the answer).\n"
        "- Document 4–5 (optional): Any additional strictly relevant documents that provide "
        "alternative but correct perspectives or examples.\n\n"
        "Query: {query}\n\n"
        "Provide the JSON output.\n"
        "Example Output Format:\n"
        "```json\n"
        "{\n"
        "  \"Plan\": \"Detailed plan applying Step 6 logic...\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...text...\",\n"
        "    \"Entity\": \"...text...\",\n"
        "    \"Example\": \"...text...\",\n"
        "    \"Other\": \"...text...\"\n"
        "  }\n"
        "}\n"
        "```\n"
    ),
    "agent_executor_v1": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Key idea:\n"
        "- Assume you already have the correct answer to the user query.\n"
        "- The documents we want are the ones that would be used as core evidence or justification for that answer.\n"
        "- These evidence documents are often more abstract than the surface query.\n\n"
        "Task:\n"
        "- First, write a 1-2 sentence Plan that states the user's core intent and what kind of evidence would justify the answer.\n"
        "- Use the context summaries only as hints (not ground truth).\n"
        "- Produce 2-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
        "\t- Propose multiple plausible theories/mechanisms.\n"
        "\t- Propose examples/analogies.\n"
        "\t- Propose other possible useful documents.\n"
        "**Output Format:**\n"
        "Output a single JSON object. The values will be concatenated to form the next query.\n"
        "```json\n"
        "{\n"
        "  \"Plan\": \"...\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...text...\",\n"
        "    \"Entity\": \"...text...\",\n"
        "    \"Example\": \"...text...\",\n"
        "    \"Other\": \"...text...\"\n"
        "  }\n"
        "}\n"
        "```\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Context Summaries:\n{gate_descs}\n"
    ),
    "agent_executor_v1_icl": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Plan:\n"
            "- Write a short Plan that states the user's core intent and what kind of evidence would justify the answer.\n"
            "\t- Identify the user's intent and answer type.\n"
            "\t- Assume you already have the correct answer to the user query.\n"
            "\t- Abstraction: The documents we want are the ones that would be used as core evidence or justification for that answer. Infer which academic terms, theories, models, examples, or canonical methods would be cited as a core evidence.\n"
        "Task:\n"
            "- Use the context summaries only as hints (not ground truth).\n"
            "- Produce multiple distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
            "- Do NOT require lexical overlap with the original query; prioritize abstract evidence.\n"
        "- Evidence forms may include (not exhaustive):\n"
            "\t- Propose multiple plausible theories/mechanisms.\n"
            "\t- Propose concrete entities/phenomena.\n"
            "\t- Propose examples/analogies.\n"
            "\t- Propose other possible useful documents.\n"
        "**Output Format:**\n"
        "Output JSON only. e.g.:\n"
        "{\n"
        "  \"Plan\": \"...\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...\",\n"
        "    \"Entity\": \"...\",\n"
        "    \"Example\": \"...\",\n"
        "  }\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Context Summaries:\n{gate_descs}\n\n"
    ),
    "agent_executor_v1_icl2": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Key idea:\n"
        "- Assume you already have the correct answer to the user query.\n"
        "- The documents we want are the ones that would be used as core evidence or justification for that answer.\n"
        "- These evidence documents are often more abstract than the surface query.\n\n"
        "Task:\n"
        "- First, write a 1-2 sentence Plan that states the user's core intent and what kind of evidence would justify the answer.\n"
        "- Use the context summaries only as hints (not ground truth).\n"
        "- Produce 2-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
        "\t- For example, propose multiple plausible theories/mechanisms, concrete entities/phenomena, or examples/analogies. Propose other possible useful documents.\n"
        "**Output Format:**\n"
        "Output a single JSON object. The values will be concatenated to form the next query.\n"
        "e.g. ```json\n"
        "{\n"
        "  \"Plan\": \"...\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...text...\",\n"
        "    \"Entity\": \"...text...\",\n"
        "    \"Example\": \"...text...\",\n"
        "    \"(Other)\": \"...text...\"\n"
        "  }\n"
        "}\n"
        "```\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Context Summaries:\n{gate_descs}\n"
    ),
    "agent_executor_v1_icl2_emr_memory": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Key idea:\n"
        "- Assume you already have the correct answer to the user query.\n"
        "- The documents we want are the ones that would be used as core evidence or justification for that answer.\n"
        "- These evidence documents are often more abstract than the surface query.\n\n"
        "Task:\n"
        "- First, write a 1-2 sentence Plan that states the user's core intent and what kind of evidence would justify the answer.\n"
        "- Use the Context Summaries and the Memory of Documents only as hints (not ground truth).\n"
        "- Use the History of Recent Actions to avoid repeating the same rewrite direction.\n"
        "- Produce 2-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
        "\t- For example, propose multiple plausible theories/mechanisms, concrete entities/phenomena, or examples/analogies. Propose other possible useful documents.\n"
        "**Output Format:**\n"
        "Output a single JSON object. The values will be concatenated to form the next query.\n"
        "e.g. ```json\n"
        "{\n"
        "  \"Plan\": \"...\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...text...\",\n"
        "    \"Entity\": \"...text...\",\n"
        "    \"Example\": \"...text...\",\n"
        "    \"(Other)\": \"...text...\"\n"
        "  }\n"
        "}\n"
        "```\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "History of Recent Actions:\n{history_actions}\n\n"
        "Memory of Documents:\n{memory_docs}\n\n"
        "Context Summaries:\n{gate_descs}\n"
    ),
    "agent_executor_v1_icl2_explore": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Key idea:\n"
        "- Assume you already have the correct answer to the user query.\n"
        "- The documents we want are the ones that would be used as core evidence or justification for that answer.\n"
        "- These evidence documents are often more abstract than the surface query.\n\n"
        "- In this exploration step, keep the original query as the anchor and look for a different but still plausible evidence route.\n\n"
        "Task:\n"
        "- First, write a 1-2 sentence Plan that states the user's core intent and what kind of evidence would justify the answer.\n"
        "- Use the context summaries only as hints (not ground truth).\n"
        # Intent: keep the prompt close to icl2 while making explore use the previous rewrite as a soft anchor rather than a hard target.
        "- Extract any useful terms or ideas from the Previous Rewritten Query, which is a soft memo of directions that were already explored.\n"
        "- Preserve any clearly useful evidence angle from it when appropriate, but do not simply repeat it.\n"
        "- Let the context summaries guide you toward a different plausible evidence direction that is still faithful to the original query.\n"
        "- Produce 2-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
        "\t- For example, propose multiple plausible theories/mechanisms, concrete entities/phenomena, or examples/analogies. Propose other possible useful documents.\n"
        "**Output Format:**\n"
        "Output a single JSON object. The values will be concatenated to form the next query.\n"
        "e.g. ```json\n"
        "{\n"
        "  \"Plan\": \"...\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...text...\",\n"
        "    \"Entity\": \"...text...\",\n"
        "    \"Example\": \"...text...\",\n"
        "    \"(Other)\": \"...text...\"\n"
        "  }\n"
        "}\n"
        "```\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Context Summaries:\n{gate_descs}\n"
    ),
    "agent_executor_v1_icl2_rubric": (
        "Relevance Definition:\n{relevance_definition}\n\n"
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Key idea:\n"
        "- Assume you already have the correct answer to the user query.\n"
        "- The documents we want are the ones that would be used as core evidence or justification for that answer.\n"
        "- These evidence documents are often more abstract than the surface query.\n\n"
        "Task:\n"
        "- First, write a 1-2 sentence Plan that states the user's core intent and what kind of evidence would justify the answer.\n"
        "- Use the context summaries only as hints (not ground truth).\n"
        "- Produce 2-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
        "\t- For example, propose multiple plausible theories/mechanisms, concrete entities/phenomena, or examples/analogies. Propose other possible useful documents.\n"
        "**Output Format:**\n"
        "Output a single JSON object. The values will be concatenated to form the next query.\n"
        "e.g. ```json\n"
        "{\n"
        "  \"Plan\": \"...\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...text...\",\n"
        "    \"Entity\": \"...text...\",\n"
        "    \"Example\": \"...text...\",\n"
        "    \"(Other)\": \"...text...\"\n"
        "  }\n"
        "}\n"
        "```\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Context Summaries:\n{gate_descs}\n"
    ),
    # Intent: open-set category generation stays abstract and avoids topic-specific key drift.
    # - domain_route_hint: subset-level routing prior (science/why vs coding vs theorem) to prevent domain mismatch.
    # - category_history: full bank of previously selected category labels/hints for stability across iterations.
    # - stability_hint: soft category-stability instruction toggled by runtime trigger (e.g., leaf-cluster condition).
    "round5_category_generator_v1": (
        "Domain Route Hint:\n{domain_route_hint}\n\n"
        "You are selecting abstraction categories for reasoning-intensive retrieval.\n\n"
        "Goal:\n"
        "- Infer what kinds of evidence are needed to justify a correct answer.\n"
        "- Prioritize topic-cluster signals over snippet-level details.\n"
        "{stability_hint}"
        "Task:\n"
        "1. Clarify the user's intent and answer type.\n"
        "2. Infer what evidence categories would best support that answer.\n"
        "- Generate up to {category_k} categories.\n"
        "- Category labels must be abstract and reusable (lowercase snake_case, 1-4 words).\n"
        "Examples of category (style reference only, not fixed labels):\n"
        "- theory, entity, example, statistical_model, mechanism, empirical_evidence, method, reference_documentation, definition\n\n"
        "Output JSON only:\n"
        "{\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Categories\": [\n"
        "    {\"label\": \"theory\", \"hint\": \"what evidence this category should contain\"},\n"
        "    {\"label\": \"entity\", \"hint\": \"...\"}\n"
        "  ]\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Retrieved Topic Cluster Summaries:\n{branch_descs}\n\n"
        "Additional Category Selection Hints:\n"
        "Category History:\n{category_history}\n\n"
        "Retrieved Document Evidence Snippets:\n{leaf_descs}\n"
    ),
    # Intent: bind rewrite keys to selected categories so downstream selector reasons over consistent abstractions.
    "round5_agent_executor_category_v1": (
        "Domain Route Hint:\n{domain_route_hint}\n\n"
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Goal:\n"
        "- Infer evidence documents needed to justify a correct answer.\n"
        "- Do NOT answer the query directly.\n\n"
        "Task:\n"
        "1. Clarify the user's intent and answer type.\n"
        "2. Infer what evidence would best support that answer.\n"
        "3. Exclude likely wrong directions that are easy to confuse with this query.\n"
        "- Use ONLY the selected category labels below as keys in Possible_Answer_Docs.\n"
        "- Output 1 to {category_k} entries.\n"
        "- Values should be retrieval hypotheses (document-like evidence statements), not final answers.\n\n"
        "Output JSON only:\n"
        "{\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "{selected_category_schema}\n"
        "  }\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Selected Categories:\n{selected_categories}\n\n"
        "Retrieved Document Evidence Snippets:\n{leaf_descs}\n\n"
    ),
    "round3_agent_executor_v1": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Plan:\n"
            "- Write a short Plan that states the user's core intent and what kind of evidence would justify the answer.\n"
            "\t- Identify the user's intent and answer type.\n"
            "\t- Assume you already have the correct answer to the user query.\n"
            "\t- Abstraction: The documents we want are the ones that would be used as core evidence or justification for that answer. Infer which academic terms, theories, models, examples, or canonical methods would be cited as a core evidence.\n"
        "Task:\n"
            "- Use the context summaries only as hints (not ground truth).\n"
            "- Produce 3-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
            "- Do NOT require lexical overlap with the original query; prioritize abstract evidence.\n"
        "- Evidence forms may include (not exhaustive):\n"
            "\t- Propose multiple plausible theories/mechanisms.\n"
            "\t- Propose concrete entities/phenomena.\n"
            "\t- Propose examples/analogies.\n"
            "\t- Propose other possible useful documents.\n"
        "**Output Format:**\n"
        "Output JSON only. e.g.:\n"
        "{\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...\",\n"
        "    \"Entity\": \"...\",\n"
        "    \"Example\": \"...\",\n"
        "    \"Other\": \"...\"\n"
        "  }\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Leaf Evidence:\n{leaf_descs}\n\n"
        "Branch Context:\n{branch_descs}\n"
    ),
    # Intent: pre-planner returns only selected categories and high-recall keywords from website_title pool.
    "round4_preplanner_v1": (
        "You are a pre-planner for reasoning-intensive retrieval.\n\n"
        "Goal:\n"
        "- Before final rewrite, extract high-recall guidance from website titles and category guide.\n\n"
        "Task:\n"
        "- Select up to {max_categories} useful categories from the corpus category guide.\n"
        "- Extract up to {max_keywords} relevant keywords from the website title pool.\n"
        "- Favor recall.\n"
        "- Output JSON only with exactly two fields.\n\n"
        "Output JSON only:\n"
        "{\n"
        "  \"Selected_Categories\": [\"...\", \"...\"],\n"
        "  \"Branch_Keywords\": [\"...\", \"...\"]\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Leaf Evidence:\n{leaf_descs}\n\n"
        "Branch Context:\n{branch_descs}\n\n"
        "Corpus category guide:\n{corpus_categories}\n\n"
        "Website title pool:\n{website_titles}\n"
    ),
    # Intent: doc_id variant keeps output schema identical while swapping the evidence-reference pool to IDs.
    "round4_preplanner_docid_v1": (
        "You are a pre-planner for reasoning-intensive retrieval.\n\n"
        "Goal:\n"
        "- Before final rewrite, extract high-recall guidance from document IDs and category guide.\n\n"
        "Task:\n"
        "- Select up to {max_categories} useful categories from the corpus category guide.\n"
        "- Extract up to {max_keywords} relevant keywords from the document ID pool.\n"
        "- Favor recall.\n"
        "- Output JSON only with exactly two fields.\n\n"
        "Output JSON only:\n"
        "{\n"
        "  \"Selected_Categories\": [\"...\", \"...\"],\n"
        "  \"Branch_Keywords\": [\"...\", \"...\"]\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Leaf Evidence:\n{leaf_descs}\n\n"
        "Branch Context:\n{branch_descs}\n\n"
        "Corpus category guide:\n{corpus_categories}\n\n"
        "Document ID pool:\n{doc_ids}\n"
    ),
    "thinkqe": (
        "Given a query, the provided passages (most of which may be incorrect or irrelevant), and the previous rewritten query, "
        "identify helpful information from the passages and refine the prior query.\n"
        "- Ensure the output directly improves retrieval for the original query.\n"
        "- Use your own knowledge when needed; do not blindly copy passages.\n"
        "- Output ONLY the rewritten query text.\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Context Summaries:\n{gate_descs}\n"
    ),
    "thinkqe_round3": (
        "Given a query, the provided passages (most of which may be incorrect or irrelevant), and the previous rewritten query, "
        "identify helpful information from the passages and refine the prior query.\n"
        "- Ensure the output directly improves retrieval for the original query.\n"
        "- Use your own knowledge when needed; do not blindly copy passages.\n"
        "- Output ONLY the rewritten query text.\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        # Intent: round3 variant explicitly binds context to leaf evidence to avoid gate_descs ambiguity.
        "Leaf Evidence:\n{leaf_descs}\n"
    ),
}

SCHEMA_PROMPT_TEMPLATE = (
    "You are defining abstraction categories for query rewriting.\n\n"
    "Given:\n"
    "- Original query\n"
    "- Document descriptions (query-agnostic summaries)\n\n"
    "Task:\n"
    "- Your task is not to answer the query.\n"
    "- Abstraction: infer which TYPE of information e.g., terms, scientific theories, mathematical "
    "models, canonical methods, or standard resources lie behind and "
    "would be cited in an answer to the question.\n"
    "- Scan corpus: use the document descriptions as hints for which kind of documents are in the corpus.\n\n"
    "- Select 3-5 abstraction category labels from document descriptions.\n"
    "- Categories must be 1-4 words, short, and non-overlapping.\n"
    "- Avoid specific terms; focus on abstract types of information.\n"
    "- Light examples of labels: "
    "theory, key entity, mathematical model, empirical/analogical evidence, example\n\n"
    "Output JSON only:\n"
    "{\n"
    "  \"schema_labels\": [\"...\", \"...\", \"...\"]\n"
    "}\n\n"
    "Original Query:\n{original_query}\n\n"
    "Document Descriptions:\n{branch_descs}\n"
)
