REWRITE_PROMPT_TEMPLATES = {
    "gate_rewrite_v1": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Key idea:\n"
        "- Assume you already have the correct answer to the user query.\n"
        "- The documents we want are the ones that would be used as core evidence or justification for that answer.\n"
        "- These evidence documents are often more abstract than the surface query.\n\n"
        "Task:\n"
        "- First, write a 1-2 sentence Plan that states the user's core intent and what kind of evidence would justify the answer.\n"
        "- Use the context summaries only as hints (not ground truth).\n"
        "- Produce 2-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
        "- Avoid near-duplicates; keep each item short and retrieval-friendly.\n"
        "- Evidence forms may include (not exhaustive): theory/mechanism, entity/fact, analogy/example, method/metric, canonical reference.\n\n"
        "Output JSON only:\n"
        "{\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Possible_Answer_Docs\": [\n"
        "    \"...\",\n"
        "    \"...\",\n"
        "    \"...\"\n"
        "  ]\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Context Summaries:\n{gate_descs}\n"
    ),
    # Intent: round3 variant keeps gate_rewrite_v1 wording identical but binds context to leaf evidence input.
    "round3_gate_rewrite_v1": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Key idea:\n"
        "- Assume you already have the correct answer to the user query.\n"
        "- The documents we want are the ones that would be used as core evidence or justification for that answer.\n"
        "- These evidence documents are often more abstract than the surface query.\n\n"
        "Task:\n"
        "- First, Analyze the user's core intent and what kind of evidence would justify the answer.\n"
        "- Use the context summaries only as hints (not ground truth).\n"
        "- Produce 2-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
        "- Avoid near-duplicates; keep each item short and retrieval-friendly.\n"
        "- Evidence forms may include (not exhaustive): theory/mechanism, entity/fact, analogy/example, method/metric, canonical reference.\n\n"
        "Output JSON with Possible_Answer_Docs only:\n"
        "{\n"
        "  \"Possible_Answer_Docs\": [\n"
        "    \"...\",\n"
        "    \"...\",\n"
        "    \"...\"\n"
        "  ]\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Context Summaries:\n{leaf_descs}\n"
    ),
    "gate_rewrite_schema_v1": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Key idea:\n"
        "- Assume you already have the correct answer to the user query.\n"
        "- The documents we want are the ones that would be used as core evidence or justification for that answer.\n"
        "- These evidence documents are often more abstract than the surface query.\n\n"
        "Task:\n"
        "- First, write a 1-2 sentence Plan that states the user's core intent, answer, and what kind of evidence would justify the answer.\n"
        "- Produce 2-5 distinct Possible_Answer_Docs, guided by the given categories.\n"
        "Output JSON only:\n"
        "{\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "{schema_kv_template}\n"
        "  }\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Context Summaries:\n{gate_descs}\n"
    ),
    "round3_action_v1": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Goal:\n"
        "- Decide whether to stay local (EXPLOIT) or change direction (EXPLORE).\n"
        "- If evidence supports the current hypothesis (previous rewrite), choose EXPLOIT.\n"
        "- If evidence is missing, contradictory, or points elsewhere, choose EXPLORE.\n\n"
        "Task:\n"
        "- Write a short Plan that follows these steps:\n"
        "  1. Identify the user's intent and answer type.\n"
        "  2. Abstraction: infer which academic terms, theories, models, or canonical methods would be cited in a correct answer.\n"
        "  3. Verification: compare the evidence against your current hypothesis.\n"
        "     - If supported -> EXPLOIT.\n"
        "     - If missing/contradictory -> EXPLORE and treat the previous rewrite as a negative constraint.\n"
        "  4. Ensure every generated document is abstract evidence (NOT surface-level restatements).\n"
        "- Action-specific behavior:\n"
        "  - EXPLOIT: Refine the current hypothesis and **use key terms from evidence as anchors**, while staying abstract.\n"
        "  - EXPLORE: Pivot to a new abstract hypothesis (different theory/framework/entity name), avoiding the failed direction.\n"
        "- Produce 3-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
        "- Do NOT require lexical overlap with the original query; prioritize abstract evidence.\n"
        "- Evidence forms may include (not exhaustive): theory/mechanism, entity/fact, analogy/example, method/metric, canonical reference.\n"
        "Output JSON only:\n"
        "{\n"
        "  \"action\": \"exploit\",\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...\",\n"
        "    \"Entity\": \"...\",\n"
        "    \"Example\": \"...\",\n"
        "    \"Other\": \"...\"\n"
        "  }\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Leaf Evidence:\n{leaf_descs}\n\n"
        "Branch Context:\n{branch_descs}\n"
    ),
    "round3_action_v1_router": (
        "You are choosing whether to stay local (EXPLOIT) or change direction (EXPLORE).\n\n"
        "Goal:\n"
        "- If evidence supports the current hypothesis (previous rewrite), choose EXPLOIT.\n"
        "- If evidence is missing, contradictory, or points elsewhere, choose EXPLORE.\n\n"
        "Task:\n"
        "- Write a short Plan that follows these steps:\n"
        "  1. Identify the user's intent and answer type.\n"
        "  2. Abstraction: infer which academic terms, theories, models, or canonical methods would be cited in a correct answer.\n"
        "  3. Verification: compare the evidence against your current hypothesis.\n"
        "     - If supported -> EXPLOIT.\n"
        "     - If missing/contradictory -> EXPLORE and treat the previous rewrite as a negative constraint.\n"
        "- Output only the action decision.\n"
        "Output JSON only:\n"
        "{\n"
        "  \"action\": \"exploit\",\n"
        "  \"Plan\": \"short reasoning\"\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Previous Possible Answer Docs:\n{previous_docs}\n\n"
        "Current Evidence (leaf top-K):\n{leaf_descs}\n\n"
        "Other Directions (non-overlap branches):\n{branch_descs}\n"
    ),
    "round3_action_v1_exploit": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Goal:\n"
        "- You MUST choose EXPLOIT.\n"
        "- Refine the current hypothesis while staying abstract.\n\n"
        "Task:\n"
        "- Write a short Plan that follows these steps:\n"
        "  1. Identify the user's intent and answer type.\n"
        "  2. Abstraction: infer which academic terms, theories, models, or canonical methods would be cited in a correct answer.\n"
        "  3. Use evidence to refine the current hypothesis and **use key terms from evidence as anchors**.\n"
        "  4. Ensure every generated document is abstract evidence (NOT surface-level restatements).\n"
        "- Produce 3-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
        "- Do NOT require lexical overlap with the original query; prioritize abstract evidence.\n"
        "- Evidence forms may include (not exhaustive): theory/mechanism, entity/fact, analogy/example, method/metric, canonical reference.\n"
        "Output JSON only:\n"
        "{\n"
        "  \"action\": \"exploit\",\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...\",\n"
        "    \"Entity\": \"...\",\n"
        "    \"Example\": \"...\",\n"
        "    \"Other\": \"...\"\n"
        "  }\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Leaf Evidence:\n{leaf_descs}\n\n"
        "Branch Context:\n{branch_descs}\n"
    ),
    "round3_action_v1_explore": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Goal:\n"
        "- You MUST choose EXPLORE.\n"
        "- Pivot to a new abstract hypothesis and avoid the failed direction.\n\n"
        "Task:\n"
        "- Write a short Plan that follows these steps:\n"
        "  1. Identify the user's intent and answer type.\n"
        "  2. Abstraction: infer which academic terms, theories, models, or canonical methods would be cited in a correct answer.\n"
        "  3. Treat the previous rewrite as a negative constraint and propose a different abstract direction.\n"
        "  4. Ensure every generated document is abstract evidence (NOT surface-level restatements).\n"
        "- Produce 3-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
        "- Do NOT require lexical overlap with the original query; prioritize abstract evidence.\n"
        "- Evidence forms may include (not exhaustive): theory/mechanism, entity/fact, analogy/example, method/metric, canonical reference.\n"
        "Output JSON only:\n"
        "{\n"
        "  \"action\": \"explore\",\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...\",\n"
        "    \"Entity\": \"...\",\n"
        "    \"Example\": \"...\",\n"
        "    \"Other\": \"...\"\n"
        "  }\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Leaf Evidence:\n{leaf_descs}\n\n"
        "Branch Context:\n{branch_descs}\n"
    ),
    "round3_free_rewrite_v2": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Key idea:\n"
        "- Assume you already have the correct answer to the user query.\n"
        "- The documents we want are the ones that would be used as core evidence or justification for that answer.\n"
        "- These evidence documents are often more abstract than the surface query.\n\n"
        "Task:\n"
        "- First, write a 1-2 sentence Plan that states the user's core intent and what kind of evidence would justify the answer.\n"
        "- Use the context summaries only as hints (not ground truth).\n"
        "- Produce 2-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
        "- Do NOT require lexical overlap with the original query; prioritize abstract evidence.\n"
        "Output JSON only:\n"
        "{\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Possible_Answer_Docs\": [\n"
        "    \"...\",\n"
        "    \"...\",\n"
        "    \"...\"\n"
        "  ]\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Leaf Evidence:\n{leaf_descs}\n\n"
        "Branch Context:\n{branch_descs}\n"
    ),
    "round3_action_v2": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Goal:\n"
        "- Decide whether to stay local (EXPLOIT), keep the current rewrite as-is (HOLD), or change direction (EXPLORE).\n"
        "- If evidence supports the current hypothesis but no update is needed, choose HOLD.\n"
        "- If evidence supports the current hypothesis and you can refine it, choose EXPLOIT.\n"
        "- If evidence is missing, contradictory, or points elsewhere, choose EXPLORE.\n\n"
        "Task:\n"
        "- Write a short Plan that follows these steps:\n"
        "  1. Identify the user's intent and answer type.\n"
        "  2. Abstraction: infer which academic terms, theories, models, or canonical methods would be cited in a correct answer.\n"
        "  3. Verification: compare the evidence against your current hypothesis.\n"
        "     - If supported and no change needed -> HOLD.\n"
        "     - If supported and refinement is needed -> EXPLOIT.\n"
        "     - If missing/contradictory -> EXPLORE and treat the previous rewrite as a negative constraint.\n"
        "  4. Ensure every generated document is abstract evidence (NOT surface-level restatements).\n"
        "- Action-specific behavior:\n"
        "  - HOLD: Keep the previous rewrite exactly; do not shift to a new terms.\n"
        "  - EXPLOIT: Refine the current hypothesis and **use key terms from evidence as anchors**, while staying abstract.\n"
        "  - EXPLORE: Pivot to a new abstract hypothesis (different theory/framework/entity name), avoiding the failed direction.\n"
        "- Produce 3-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
        "- Do NOT require lexical overlap with the original query; prioritize abstract evidence.\n"
        "- Evidence forms may include (not exhaustive): theory/mechanism, entity/fact, analogy/example, method/metric, canonical reference.\n"
        "Output JSON only:\n"
        "{\n"
        "  \"action\": \"hold\",\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...\",\n"
        "    \"Entity\": \"...\",\n"
        "    \"Example\": \"...\",\n"
        "    \"Other\": \"...\"\n"
        "  }\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Leaf Evidence:\n{leaf_descs}\n\n"
        "Branch Context:\n{branch_descs}\n"
    ),
    "round3_action_v3": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Goal:\n"
        "- Decide whether to stay local (EXPLOIT), delete one or more abstraction categories (PRUNE), or change direction (EXPLORE).\n"
        "- If evidence supports the current hypothesis and you can refine it, choose EXPLOIT.\n"
        "- If a category is irrelevant or noisy, choose PRUNE and remove that category from Possible_Answer_Docs.\n"
        "- If evidence is missing, contradictory, or points elsewhere, choose EXPLORE.\n\n"
        "Task:\n"
        "- Write a short Plan that follows these steps:\n"
        "  1. Identify the user's intent and answer type.\n"
        "  2. Abstraction: infer which academic terms, theories, models, or canonical methods would be cited in a correct answer.\n"
        "  3. Verification: compare the evidence against your current hypothesis.\n"
        "     - If supported -> EXPLOIT.\n"
        "     - If missing/contradictory -> EXPLORE and treat the previous rewrite as a negative constraint.\n"
        "     - If a category adds noise -> PRUNE that category.\n"
        "  4. Ensure every generated document is abstract evidence (NOT surface-level restatements).\n"
        "- Action-specific behavior:\n"
        "  - EXPLOIT: Refine the current hypothesis and **use key terms from evidence as anchors**, while staying abstract.\n"
        "  - EXPLORE: Pivot to a new abstract hypothesis (different theory/framework/entity name), avoiding the failed direction.\n"
        "  - PRUNE: Remove one or more abstraction categories by omitting them or leaving them empty in Possible_Answer_Docs.\n"
        "- Produce 3-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
        "- Do NOT require lexical overlap with the original query; prioritize abstract evidence.\n"
        "- Evidence forms may include (not exhaustive): theory/mechanism, entity/fact, analogy/example, method/metric, canonical reference.\n"
        "Output JSON only:\n"
        "{\n"
        "  \"action\": \"prune\",\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...\",\n"
        "    \"Entity\": \"...\",\n"
        "    \"Example\": \"...\",\n"
        "    \"Other\": \"...\"\n"
        "  }\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Leaf Evidence:\n{leaf_descs}\n\n"
        "Branch Context:\n{branch_descs}\n"
    ),
    "round3_action_levels_v1": (
        "You are rewriting a search query for reasoning-intensive retrieval with per-category actions.\n\n"
        "Goal:\n"
        "- Decide EXPLOIT/EXPLORE/PRUNE for each abstraction category.\n"
        "- EXPLOIT if evidence supports the previous hypothesis for that category.\n"
        "- EXPLORE if evidence is missing/contradictory or points elsewhere.\n"
        "- PRUNE if the category is not useful for this query.\n\n"
        "Inputs:\n"
        "- Original Query\n"
        "- Previous Possible Answer Docs (per category)\n"
        "- Leaf Evidence (retrieved summaries)\n"
        "- Branch Context (optional)\n\n"
        "Task:\n"
        "- Write a short Plan following these steps:\n"
        "  1. Identify user intent and answer type.\n"
        "  2. Abstraction: infer which theories, models, entities, or canonical methods would be cited in a correct answer.\n"
        "  3. Verification: compare evidence against previous hypotheses per category.\n"
        "  4. Ensure every generated document is abstract evidence (not surface-level restatement).\n"
        "- Action-specific behavior per category:\n"
        "  - EXPLOIT: Refine the previous doc and **use key terms from evidence** while staying abstract.\n"
        "  - EXPLORE: Pivot to a new abstract hypothesis (different theory/framework/entity), avoiding the failed direction.\n"
        "  - PRUNE: Remove this category.\n"
        "- Produce 3-5 distinct Possible_Answer_Docs total (across categories).\n"
        "- Do NOT require lexical overlap with the original query; prioritize abstract evidence.\n\n"
        "Output JSON only:\n"
        "{\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Actions\": {\n"
        "    \"Theory\": \"EXPLOIT\",\n"
        "    \"Entity\": \"EXPLORE\",\n"
        "    \"Example\": \"PRUNE\",\n"
        "    \"Other\": \"EXPLOIT\"\n"
        "  },\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...\",\n"
        "    \"Entity\": \"...\",\n"
        "    \"Example\": \"...\",\n"
        "    \"Other\": \"...\"\n"
        "  }\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Possible Answer Docs:\n{previous_docs}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Leaf Evidence:\n{leaf_descs}\n\n"
        "Branch Context:\n{branch_descs}\n"
    ),
    "stepback_json": (
        "Given a query, the provided passages (most of which may be incorrect or irrelevant), and the previous round's answer (if any), "
        "your goal is to analyze the candidate passages retrieved for the query, "
        "identify which of them are strictly relevant to the user's true intent, "
        "and then refine the set of answer documents accordingly. "
        "Each refined document must be strictly relevant: it should either contain the "
        "exact answer or provide abstractive-level theory, evidence, or background that is "
        "necessary for that answer.\n\n"
        "Output Format:\n"
        "You must output a single JSON object with the following keys:\n"
        "- \"Plan\": A detailed string where you analyze availability of information and plan your selection. Follow the planning steps below.\n"
        "- \"Possible_Answer_Docs\": A JSON object with keys as document types (\"Theory\", \"Entity\", \"Example\", \"Other\") and values as strings representing distinct answer documents.\n\n"
        "Planning Steps (for the \"Plan\" field):\n"
        "1. Precisely identify what information the user is seeking "
        "(e.g., why / how / what / what is this called / which part) and what type of "
        "answer would satisfy them (e.g., concept name, theory, explanation, concrete "
        "entity, worked example).\n"
        "2. If the query is explicitly or implicitly asking 'what is this called?', "
        "generate diverse hypotheses for the name of the phenomenon, object, or concept.\n"
        "3. Abstraction: infer which academic terms, scientific theories, mathematical "
        "models, canonical methods, or standard resources lie behind this question and "
        "would be cited in a strictly correct answer.\n"
        "4. Consider alternative ways the answer might be supported: a direct definition, "
        "background theory, canonical examples, or reference websites.\n"
        "5. For causal or explanatory questions (why/how), identify multiple theoretical "
        "frameworks that offer different explanations, including mainstream, alternative, "
        "and controversial perspectives if mentioned in the query.\n"
        "6. For each Candidate Passage, judge which part of the user's query does the passage address. Then, "
        "identify the common wrong direction (topic, answer type, or framing) suggested by "
        "the Candidate Passages, and treat this as a negative constraint. Plan how to "
        "refine the answer documents to avoid that direction and instead explore a different, more "
        "plausible interpretation aligned with the user's wording.\n"
        "Ensure that every generated document contributes directly and strictly to such an "
        "answer (no loosely related or merely interesting content).\n\n"
        "Final Answer Requirements (for the \"Answer documents\" field):\n"
        "Include 3-5 distinct answer-document entries:\n"
        "- 1: Concept/Theory-focused (academic terms, principles, models).\n"
        "- 2: Entity/Fact-focused (specific names, objects, or concrete facts).\n"
        "- 3: Broad Context/Evidence-focused (surveys, experiments, or background "
        "that support the answer).\n"
        "- Document 4–5 (optional): Any additional strictly relevant documents that provide "
        "alternative but correct perspectives or examples.\n\n"
        "Query: {query}\n\n"
        "Provide the JSON output.\n"
        "Example Output Format:\n"
        "```json\n"
        "{\n"
        "  \"Plan\": \"Detailed plan applying Step 6 logic...\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...text...\",\n"
        "    \"Entity\": \"...text...\",\n"
        "    \"Example\": \"...text...\",\n"
        "    \"Other\": \"...text...\"\n"
        "  }\n"
        "}\n"
        "```\n"
    ),
    "agent_executor_v1": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Key idea:\n"
        "- Assume you already have the correct answer to the user query.\n"
        "- The documents we want are the ones that would be used as core evidence or justification for that answer.\n"
        "- These evidence documents are often more abstract than the surface query.\n\n"
        "Task:\n"
        "- First, write a 1-2 sentence Plan that states the user's core intent and what kind of evidence would justify the answer.\n"
        "- Use the context summaries only as hints (not ground truth).\n"
        "- Produce 2-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
        "\t- Propose multiple plausible theories/mechanisms.\n"
        "\t- Propose examples/analogies.\n"
        "\t- Propose other possible useful documents.\n"
        "**Output Format:**\n"
        "Output a single JSON object. The values will be concatenated to form the next query.\n"
        "```json\n"
        "{\n"
        "  \"Plan\": \"...\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...text...\",\n"
        "    \"Entity\": \"...text...\",\n"
        "    \"Example\": \"...text...\",\n"
        "    \"Other\": \"...text...\"\n"
        "  }\n"
        "}\n"
        "```\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Context Summaries:\n{gate_descs}\n"
    ),
    "round3_agent_executor_v1": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Plan:\n"
            "- Write a short Plan that states the user's core intent and what kind of evidence would justify the answer.\n"
            "\t- Identify the user's intent and answer type.\n"
            "\t- Assume you already have the correct answer to the user query.\n"
            "\t- Abstraction: The documents we want are the ones that would be used as core evidence or justification for that answer. Infer which academic terms, theories, models, examples, or canonical methods would be cited as a core evidence.\n"
        "Task:\n"
            "- Use the context summaries only as hints (not ground truth).\n"
            "- Produce 3-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
            "- Do NOT require lexical overlap with the original query; prioritize abstract evidence.\n"
        "- Evidence forms may include (not exhaustive):\n"
            "\t- Propose multiple plausible theories/mechanisms.\n"
            "\t- Propose concrete entities/phenomena.\n"
            "\t- Propose examples/analogies.\n"
            "\t- Propose other possible useful documents.\n"
        "**Output Format:**\n"
        "Output JSON only. e.g.:\n"
        "{\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...\",\n"
        "    \"Entity\": \"...\",\n"
        "    \"Example\": \"...\",\n"
        "    \"Other\": \"...\"\n"
        "  }\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Leaf Evidence:\n{leaf_descs}\n\n"
        "Branch Context:\n{branch_descs}\n"
    ),
    # Intent: pre-planner returns only selected categories and high-recall keywords from website_title pool.
    "round4_preplanner_v1": (
        "You are a pre-planner for reasoning-intensive retrieval.\n\n"
        "Goal:\n"
        "- Before final rewrite, extract high-recall guidance from website titles and category guide.\n\n"
        "Task:\n"
        "- Select up to {max_categories} useful categories from the corpus category guide.\n"
        "- Extract up to {max_keywords} relevant keywords from the website title pool.\n"
        "- Favor recall.\n"
        "- Output JSON only with exactly two fields.\n\n"
        "Output JSON only:\n"
        "{\n"
        "  \"Selected_Categories\": [\"...\", \"...\"],\n"
        "  \"Branch_Keywords\": [\"...\", \"...\"]\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Leaf Evidence:\n{leaf_descs}\n\n"
        "Branch Context:\n{branch_descs}\n\n"
        "Corpus category guide:\n{corpus_categories}\n\n"
        "Website title pool:\n{website_titles}\n"
    ),
    # Intent: doc_id variant keeps output schema identical while swapping the evidence-reference pool to IDs.
    "round4_preplanner_docid_v1": (
        "You are a pre-planner for reasoning-intensive retrieval.\n\n"
        "Goal:\n"
        "- Before final rewrite, extract high-recall guidance from document IDs and category guide.\n\n"
        "Task:\n"
        "- Select up to {max_categories} useful categories from the corpus category guide.\n"
        "- Extract up to {max_keywords} relevant keywords from the document ID pool.\n"
        "- Favor recall.\n"
        "- Output JSON only with exactly two fields.\n\n"
        "Output JSON only:\n"
        "{\n"
        "  \"Selected_Categories\": [\"...\", \"...\"],\n"
        "  \"Branch_Keywords\": [\"...\", \"...\"]\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Leaf Evidence:\n{leaf_descs}\n\n"
        "Branch Context:\n{branch_descs}\n\n"
        "Corpus category guide:\n{corpus_categories}\n\n"
        "Document ID pool:\n{doc_ids}\n"
    ),
    # Intent: v5 keeps v1 structure and injects corpus-side category priors from category_registry_category_assign_v2.json.
    # Intent: allow level1 or level2 registry labels as JSON keys so routing follows type taxonomy, not topic strings.
    # Intent: force values to be concrete retrieval hypotheses (not category-label echoes) to prevent collapsed rewrites.
    "round3_agent_executor_v5": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Plan:\n"
            "- Write a short Plan that states the user's core intent and what kind of evidence would justify the answer.\n"
            "\t- Identify the user's intent and answer type.\n"
            "\t- Assume you already have the correct answer to the user query.\n"
            "\t- Abstraction: The documents we want are the ones that would be used as core evidence or justification for that answer. Infer which academic terms, theories, models, examples, or canonical methods would be cited as a core evidence.\n"
        "Task:\n"
            "- Use the context summaries only as hints (not ground truth).\n"
            "- Produce 3-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
            "- Use the corpus category guide as routing prior.\n"
            "- For Possible_Answer_Docs 'keys', use only labels from the corpus guide.\n"
            "\t- Allowed keys: level1 labels and level2 labels listed under those level1 labels.\n"
            "\t- You may mix level1 and level2 keys in one output.\n"
            "- For Possible_Answer_Docs 'values', write concrete possible answer docs.\n"
            "\t- Each value must be a specific document sentence(s).\n"
            "- Do NOT require lexical overlap with the original query; prioritize abstract evidence.\n"
        "- Corpus category guide:\n"
            "{corpus_categories}\n"
        "- Pre-planner hint (selected categories + relevant keywords):\n"
            "{preplanner_hint}\n"
        "**Output Format:**\n"
        "Output JSON only. e.g.:\n"
        "{\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"<selected_corpus_category_label_1>\": \"...\",\n"
        "    \"<selected_corpus_category_label_2>\": \"...\",\n"
        "    \"<selected_corpus_category_label_3>\": \"...\"\n"
        "  }\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Leaf Evidence:\n{leaf_descs}\n\n"
        "Branch Context:\n{branch_descs}\n"
    ),
    "round3_agent_executor_v4": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Plan:\n"
            "- Write a short Plan that states the user's core intent and what kind of evidence would justify the answer.\n"
            "\t- Identify the user's intent (why, what, how. There can be multiple intents).\n"
            "\t- Assume you already have the correct answer to the user query.\n"
            "\t- Abstraction: The documents we want are the ones that would be used as core evidence or justification for that answer. Infer which academic terms, theories, models, examples, or canonical methods would be cited as a core evidence.\n"
        "Task:\n"
            "- Use the retrieved documents only as hints (not ground truth).\n"
            "- Produce 3-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
            "- Do NOT require lexical overlap with the original query; prioritize abstract evidence.\n"
        "- Evidence forms may include (not exhaustive):\n"
            "\t- Propose plausible theories.\n"
            "\t- Propose concrete methods/mechanisms.\n"
            "\t- Propose examples/analogies.\n"
            "\t- Propose other possible useful documents.\n"
        "**Output Format:**\n"
        "Output JSON only. e.g.:\n"
        "{\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...\",\n"
        "    \"Method\": \"...\",\n"
        "    \"Example\": \"...\",\n"
        "    \"Other\": \"...\"\n"
        "  }\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Documents from previous query:\n{leaf_descs}\n\n"
    ),
    # Intent: v3 isolates one variable from v1: fixed keys vs model-selected keys.
    "round3_agent_executor_v3": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Plan:\n"
            "- Write a short Plan that states the user's core intent and what kind of evidence would justify the answer.\n"
            "\t- Identify the user's intent and answer type.\n"
            "\t- Assume you already have the correct answer to the user query.\n"
            "\t- Abstraction: The documents we want are the ones that would be used as core evidence or justification for that answer. Infer which academic terms, theories, models, examples, or canonical methods would be cited as a core evidence.\n"
        "Task:\n"
            "- Use the context summaries only as hints (not ground truth).\n"
            "- Produce 1-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
            "- Do NOT require lexical overlap with the original query; prioritize abstract evidence.\n"
            "- Choose key names for Possible_Answer_Docs yourself, but keep them abstract.\n"
            "- Key naming rule: use coarse-grained category names only (e.g., theory, statistical_model, entity, example, mechanism, method, empirical_evidence).\n"
            "- Do NOT use domain-specific or overly specific key names (e.g., light_adaptation_theory, bee_behavior_model).\n"
            "- Key format: lowercase snake_case, 1-2 words.\n"
        "- Evidence forms may include (not exhaustive):\n"
            "\t- Propose multiple plausible theories/mechanisms.\n"
            "\t- Propose concrete entities/phenomena.\n"
            "\t- Propose examples/analogies.\n"
            "\t- Propose other possible useful documents.\n"
        "**Output Format:**\n"
        "Output JSON only. e.g.:\n"
        "{\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"<abstract key 1>\": \"...\",\n"
        "    \"<abstract key 2>\": \"...\",\n"
        "    \"<abstract key 3>\": \"...\"\n"
        "  }\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Leaf Evidence:\n{leaf_descs}\n\n"
        "Branch Context:\n{branch_descs}\n"
    ),
    # Intent: v2 emits role-specific rewrites directly under Possible_Answer_Docs with dynamic role keys.
    "round3_agent_executor_v2": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Goal:\n"
        "- Do NOT just answer the user query.\n"
        "- Infer what evidence would be needed to justify a correct answer.\n\n"
        "Domain Route (selected from subset metadata):\n"
        "{domain_route_hint}\n\n"
        "Evidence Roles (choose only what is needed; multiple roles are allowed):\n"
        "1. ConceptTheory\n"
        "2. DefinitionNaming\n"
        "3. ProcedureRecipe\n"
        "4. ReferenceDocumentation\n"
        "5. WorkedExample\n"
        "6. EmpiricalEvidence\n\n"
        "Task:\n"
        "- Write a short Plan in 1-2 sentences with this format:\n"
        "  Intent: <user intent>. AnswerType: <required answer type>. EvidenceNeed: <what evidence should be retrieved>.\n"
        "- Select 1-4 roles from the 6 roles above.\n"
        "- Use only the 6 roles above. Do NOT create extra roles.\n"
        "- For each selected role, write one role-specific evidence hypothesis for retrieval.\n"
        "- The goal is useful evidence direction, even when exact technical anchor terms are unknown.\n"
        "- If exact terms are uncertain, provide descriptive concepts plus 2-3 candidate phrases/synonyms.\n"
        "- Put those role-specific retrieval hypotheses directly in Possible_Answer_Docs using selected role names as keys.\n"
        "- Use context summaries as hints only (not ground truth).\n\n"
        "Guidance examples (do not copy; only style reference):\n"
        "- Query style: why dough rises slowly in a cold kitchen\n"
        "  -> ConceptTheory: reaction kinetics in low temperature.\n"
        "- Query style: monthly counts of rare city incidents\n"
        "  -> ConceptTheory: Poisson distribution\n\n"
        "Output JSON only:\n"
        "(Template example; keys must be replaced by the selected role names.)\n"
        "{\n"
        "  \"Plan\": \"Intent: ... AnswerType: ... EvidenceNeed: ...\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"<SelectedRoleName1>\": \"what evidence this role should contain; candidate retrieval phrases: phrase1 | phrase2\",\n"
        "    \"<SelectedRoleName2>\": \"what evidence this role should contain; candidate retrieval phrases: phrase1 | phrase2\"\n"
        "    ...\n"
        "  }\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Leaf Evidence:\n{leaf_descs}\n\n"
        "Branch Context:\n{branch_descs}\n"
    ),
    "baseline_round3_action_v1": (
        "You are rewriting a search query for reasoning-intensive retrieval.\n\n"
        "Goal:\n"
        "- Decide whether to stay local (EXPLOIT) or change direction (EXPLORE).\n"
        "- If evidence supports the current hypothesis (previous rewrite), choose EXPLOIT.\n"
        "- If evidence is missing, contradictory, or points elsewhere, choose EXPLORE.\n\n"
        "Task:\n"
        "- Write a short Plan that follows these steps:\n"
        "  1. Identify the user's intent and answer type.\n"
        "  2. Abstraction: infer which academic terms, theories, models, or canonical methods would be cited in a correct answer.\n"
        "  3. Verification: compare the evidence against your current hypothesis.\n"
        "     - If supported -> EXPLOIT.\n"
        "     - If missing/contradictory -> EXPLORE and treat the previous rewrite as a negative constraint.\n"
        "  4. Ensure every generated document is abstract evidence (NOT surface-level restatements).\n"
        "- Action-specific behavior:\n"
        "  - EXPLOIT: Refine the current hypothesis and **use key terms from evidence as anchors**, while staying abstract.\n"
        "  - EXPLORE: Pivot to a new abstract hypothesis (different theory/framework/entity name), avoiding the failed direction.\n"
        "- Produce 3-5 distinct Possible_Answer_Docs that could serve as evidence for the assumed correct answer.\n"
        "- Do NOT require lexical overlap with the original query; prioritize abstract evidence.\n"
        "- Evidence forms may include (not exhaustive): theory/mechanism, entity/fact, analogy/example, method/metric, canonical reference.\n"
        "Output JSON only:\n"
        "{\n"
        "  \"action\": \"exploit\",\n"
        "  \"Plan\": \"short reasoning\",\n"
        "  \"Possible_Answer_Docs\": {\n"
        "    \"Theory\": \"...\",\n"
        "    \"Entity\": \"...\",\n"
        "    \"Example\": \"...\",\n"
        "    \"Other\": \"...\"\n"
        "  }\n"
        "}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Context Summaries:\n{gate_descs}\n"
    ),
    "thinkqe": (
        "Given a query, the provided passages (most of which may be incorrect or irrelevant), and the previous rewritten query, "
        "identify helpful information from the passages and refine the prior query.\n"
        "- Ensure the output directly improves retrieval for the original query.\n"
        "- Use your own knowledge when needed; do not blindly copy passages.\n"
        "- Output ONLY the rewritten query text.\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        "Context Summaries:\n{gate_descs}\n"
    ),
    "thinkqe_round3": (
        "Given a query, the provided passages (most of which may be incorrect or irrelevant), and the previous rewritten query, "
        "identify helpful information from the passages and refine the prior query.\n"
        "- Ensure the output directly improves retrieval for the original query.\n"
        "- Use your own knowledge when needed; do not blindly copy passages.\n"
        "- Output ONLY the rewritten query text.\n\n"
        "Original Query:\n{original_query}\n\n"
        "Previous Rewritten Query:\n{previous_rewrite}\n\n"
        # Intent: round3 variant explicitly binds context to leaf evidence to avoid gate_descs ambiguity.
        "Leaf Evidence:\n{leaf_descs}\n"
    ),
    "round3_action_oracle_select_v1": (
        "You are judging which retrieval result (explore vs exploit) is more likely to answer the query.\n\n"
        "Given:\n"
        "- Original Query\n"
        "- Explore rewrite + top-10 retrieved leaf descriptions\n"
        "- Exploit rewrite + top-10 retrieved leaf descriptions\n\n"
        "Task:\n"
        "- Choose which result set (explore vs exploit) is more likely to contain evidence that answers the query.\n"
        "- Base your decision on relevance and coverage.\n\n"
        "Output JSON only:\n"
        "{{\n"
        "  \"choice\": \"explore\" or \"exploit\"\n"
        "}}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Explore Rewrite:\n{explore_rewrite}\n\n"
        "Explore Top-10:\n{explore_descs}\n\n"
        "Exploit Rewrite:\n{exploit_rewrite}\n\n"
        "Exploit Top-10:\n{exploit_descs}\n"
    ),
    "round3_action_oracle_rerank_v1": (
        "You are reranking retrieval results for reasoning-intensive QA.\n\n"
        "Given:\n"
        "- Original Query\n"
        "- Explore rewrite + top-10 retrieved leaf descriptions (E1..E10)\n"
        "- Exploit rewrite + top-10 retrieved leaf descriptions (X1..X10)\n\n"
        "Task:\n"
        "- Produce a single ranked list of the most relevant items.\n"
        "- Prefer items that would be directly cited in a correct answer.\n"
        "- Return up to 10 items.\n\n"
        "Output JSON only:\n"
        "{{\n"
        "  \"ranking\": [\"E1\", \"X2\", \"E3\"]\n"
        "}}\n\n"
        "Original Query:\n{original_query}\n\n"
        "Explore Rewrite:\n{explore_rewrite}\n\n"
        "Explore Top-10:\n{explore_descs}\n\n"
        "Exploit Rewrite:\n{exploit_rewrite}\n\n"
        "Exploit Top-10:\n{exploit_descs}\n"
    )
}

SCHEMA_PROMPT_TEMPLATE = (
    "You are defining abstraction categories for query rewriting.\n\n"
    "Given:\n"
    "- Original query\n"
    "- Document descriptions (query-agnostic summaries)\n\n"
    "Task:\n"
    "- Your task is not to answer the query.\n"
    "- Abstraction: infer which TYPE of information e.g., terms, scientific theories, mathematical "
    "models, canonical methods, or standard resources lie behind and "
    "would be cited in an answer to the question.\n"
    "- Scan corpus: use the document descriptions as hints for which kind of documents are in the corpus.\n\n"
    "- Select 3-5 abstraction category labels from document descriptions.\n"
    "- Categories must be 1-4 words, short, and non-overlapping.\n"
    "- Avoid specific terms; focus on abstract types of information.\n"
    "- Light examples of labels: "
    "theory, key entity, mathematical model, empirical/analogical evidence, example\n\n"
    "Output JSON only:\n"
    "{\n"
    "  \"schema_labels\": [\"...\", \"...\", \"...\"]\n"
    "}\n\n"
    "Original Query:\n{original_query}\n\n"
    "Document Descriptions:\n{branch_descs}\n"
)
